# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
one_dimensional_array = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])


# Create a 3-dimensional Numpy array using np.array()
three_dimensional_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
shape = one_dimensional_array.shape
num_dimensions = one_dimensional_array.ndim
data_type = one_dimensional_array.dtype
size = one_dimensional_array.size
array_type = type(one_dimensional_array)
print("Shape:", shape)
print("Number of Dimensions:", num_dimensions)
print("Data Type:", data_type)
print("Size:", size)
print("Type:", array_type)

Shape: (5,)
Number of Dimensions: 1
Data Type: int32
Size: 5
Type: <class 'numpy.ndarray'>


In [5]:
# Attributes of 2-dimensional array
shape = two_dimensional_array.shape
num_dimensions = two_dimensional_array.ndim
data_type = two_dimensional_array.dtype
size = two_dimensional_array.size
array_type = type(two_dimensional_array)
print("Shape:", shape)
print("Number of Dimensions:", num_dimensions)
print("Data Type:", data_type)
print("Size:", size)
print("Type:", array_type)

Shape: (2, 3)
Number of Dimensions: 2
Data Type: int32
Size: 6
Type: <class 'numpy.ndarray'>


In [6]:
# Attributes of 3-dimensional array
shape = three_dimensional_array.shape
num_dimensions = three_dimensional_array.ndim
data_type = three_dimensional_array.dtype
size = three_dimensional_array.size
array_type = type(three_dimensional_array)
print("Shape:", shape)
print("Number of Dimensions:", num_dimensions)
print("Data Type:", data_type)
print("Size:", size)
print("Type:", array_type)

Shape: (2, 2, 3)
Number of Dimensions: 3
Data Type: int32
Size: 12
Type: <class 'numpy.ndarray'>


In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# Create a DataFrame from the 1D NumPy array
df = pd.DataFrame({'Column_Name': one_dimensional_array})

# Print the DataFrame
print(df)

   Column_Name
0            1
1            2
2            3
3            4
4            5


In [8]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2, 3))
zeros_array 

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
array_with_step = np.arange(0, 100, 3)
array_with_step 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr1 = np.random.randint(0, 11, size=(2, 7))
arr1

array([[ 8,  0, 10, 10,  9,  2,  6],
       [ 3,  8,  2,  4,  2,  6,  4]])

In [28]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr2 = np.random.rand(3, 5)
arr2

array([[0.45049925, 0.01326496, 0.94220176, 0.56328822, 0.3854165 ],
       [0.01596625, 0.23089383, 0.24102547, 0.68326352, 0.60999666],
       [0.83319491, 0.17336465, 0.39106061, 0.18223609, 0.75536141]])

In [29]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
arr3 = np.random.randint(0, 11, size=(4, 6))
arr3

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr4 = np.random.randint(1, 11, size=(3, 7))

# Find the unique numbers in the array you just created
idx = np.unique(arr4, return_index=True)[1]

In [36]:
# Find the 0'th index of the latest array you created
value_at_index_0 = arr4[0]

In [37]:
# Get the first 2 rows of latest array you created
rows = arr4[:2]

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
vals = rows[:, :2]

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr5 = np.random.randint(0, 11, size=(3, 5))

In [40]:
# Add the two arrays together
sum1 = arr4 + arr5

ValueError: operands could not be broadcast together with shapes (3,7) (3,5) 

In [46]:
# Create another array of ones of shape (5, 3)
arr6 = np.ones((3, 5))

In [47]:
# Try add the array of ones and the other most recent array together
sum = arr5 + arr6

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [48]:
# Create another array of ones of shape (3, 5)
arr7 = np.ones((3, 5))

In [69]:
# Subtract the new array of ones from the other most recent array
sub = sum - arr7
sub

array([[9., 1., 9., 3., 7.],
       [6., 8., 7., 4., 1.],
       [4., 7., 9., 8., 8.]])

In [70]:
# Multiply the ones array with the latest array
mul = sub * arr7
mul

array([[9., 1., 9., 3., 7.],
       [6., 8., 7., 4., 1.],
       [4., 7., 9., 8., 8.]])

In [71]:
# Take the latest array to the power of 2 using '**'
sqr = mul**2
sqr

array([[81.,  1., 81.,  9., 49.],
       [36., 64., 49., 16.,  1.],
       [16., 49., 81., 64., 64.]])

In [68]:
# Do the same thing with np.square()
npSqur = np.square(mul)
npSqur

array([[81.,  1., 81.,  9., 49.],
       [36., 64., 49., 16.,  1.],
       [16., 49., 81., 64., 64.]])

In [72]:
# Find the mean of the latest array using np.mean()
mean = np.mean(npSqur)
mean

44.06666666666667

In [73]:
# Find the maximum of the latest array using np.max()
Max = np.max(npSqur)
Max

81.0

In [74]:
# Find the minimum of the latest array using np.min()
Min = np.min(npSqur)
Min

1.0

In [75]:
# Find the standard deviation of the latest array
std = np.std(npSqur)
std

28.209848556054947

In [76]:
# Find the variance of the latest array
var = np.var(npSqur)
var

795.7955555555553

In [77]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = npSqur.reshape(3, 5, 1)
reshaped_array

array([[[81.],
        [ 1.],
        [81.],
        [ 9.],
        [49.]],

       [[36.],
        [64.],
        [49.],
        [16.],
        [ 1.]],

       [[16.],
        [49.],
        [81.],
        [64.],
        [64.]]])

In [78]:
# Transpose the latest array
transposed_array = reshaped_array.T
transposed_array 

array([[[81., 36., 16.],
        [ 1., 64., 49.],
        [81., 49., 81.],
        [ 9., 16., 64.],
        [49.,  1., 64.]]])

What does the transpose do?

In [79]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(0, 11, size=(3, 3))
array2 = np.random.randint(0, 11, size=(3, 2))


In [80]:
# Perform a dot product on the two newest arrays you created
dot_product_result = np.dot(array1, array2)
dot_product_result 

array([[ 97,  60],
       [116,  86],
       [103,  76]])

In [83]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3 = np.random.randint(0, 11, size=(4, 3))
array4 = np.random.randint(0, 11, size=(4, 3))

In [84]:
# Perform a dot product on the two newest arrays you created
dot_product_result2 = np.dot(array3, array4)
dot_product_result2 

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [85]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array3 = array3.T
dot_product_result3 = np.dot(array3, array4)
dot_product_result3 

array([[141, 126, 156],
       [178, 134, 172],
       [178, 130, 212]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [87]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array5 = np.random.randint(0, 11, size=(10, 5))
array6 = np.random.randint(0, 11, size=(10, 5))
print(array5)
print(array6)

In [89]:
# Compare the two arrays with '>'
comparison_result = array5 > array6
comparison_result

array([[False, False,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True,  True],
       [False,  True, False, False, False],
       [ True, False,  True, False, False],
       [False, False,  True, False, False],
       [ True,  True, False, False, False],
       [ True,  True, False,  True, False],
       [ True, False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [90]:
# Compare the two arrays with '>='
comparison_result = array5 >= array6
comparison_result

array([[False, False,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True,  True],
       [ True,  True, False, False, False],
       [ True,  True,  True, False, False],
       [False, False,  True, False,  True],
       [ True,  True, False, False, False],
       [ True,  True, False,  True, False],
       [ True, False, False,  True,  True]])

In [92]:
# Find which elements of the first array are greater than 7
elements_greater_than_7 = array5[array5 > 7]
elements_greater_than_7

array([ 8, 10,  8,  8,  8, 10])

In [96]:
# Which parts of each array are equal? (try using '==')
equal_elements = array5 == array6
equal_elements

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [97]:
# Sort one of the arrays you just created in ascending order
sorted_array6 = np.sort(array6)
sorted_array6

array([[ 0,  1,  4, 10, 10],
       [ 0,  2,  2,  3,  4],
       [ 0,  0,  2,  4,  5],
       [ 0,  4,  4,  7,  8],
       [ 0,  2,  3,  4,  6],
       [ 0,  1,  2,  8,  9],
       [ 2,  5,  7,  7,  9],
       [ 1,  1,  5,  6, 10],
       [ 0,  1,  7,  9,  9],
       [ 0,  5,  6,  8, 10]])

In [98]:
# Sort the indexes of one of the arrays you just created
sorted_indices = np.argsort(array6)
sorted_indices

array([[4, 2, 3, 0, 1],
       [0, 2, 4, 3, 1],
       [0, 1, 4, 2, 3],
       [3, 1, 4, 2, 0],
       [1, 0, 2, 3, 4],
       [0, 2, 1, 3, 4],
       [2, 0, 3, 4, 1],
       [0, 3, 1, 2, 4],
       [3, 1, 4, 0, 2],
       [0, 3, 4, 1, 2]], dtype=int64)

In [99]:
# Find the index with the maximum value in one of the arrays you've created
max_value_index = np.unravel_index(np.argmax(array6), array6.shape)
max_value_index

(0, 0)

In [100]:
# Find the index with the minimum value in one of the arrays you've created
min_value_index = np.unravel_index(np.argmin(array6), array6.shape)
min_value_index

(0, 4)

In [101]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_value_indices = np.argmax(array6, axis=1)
max_value_indices

array([0, 1, 3, 0, 4, 4, 1, 4, 0, 2], dtype=int64)

In [102]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_value_indices = np.argmin(array6, axis=0)
min_value_indices

array([1, 2, 0, 3, 0], dtype=int64)

In [107]:
# Create an array of normally distributed random numbers
normally_distributed_random_numbers = np.random.randn(100)
normally_distributed_random_numbers

array([ 0.30444912,  0.25720749,  0.02393181,  0.87191399,  1.43735633,
        0.00730637,  1.33088133,  0.98820261,  0.23229616,  0.17618092,
       -1.15256537, -1.50076839,  0.1650228 , -0.85592892, -0.03963614,
       -0.53466274, -1.7884965 ,  0.35730454, -0.41453181,  0.08019871,
       -0.89312027, -0.33481725,  1.56038014,  0.128551  ,  0.54957635,
       -1.27087181,  2.38903596,  1.84341376,  1.36343549,  0.82876598,
        0.01514328,  0.44207402,  1.04801974, -0.62856975, -0.44449874,
       -1.66913236, -0.77181908,  1.66130173, -0.33424709, -0.31784691,
        0.31776703, -1.61222731,  0.94538169,  1.26640686,  0.37729627,
        1.65135099, -1.32683177,  1.8437158 , -0.7307414 , -1.27991973,
       -0.23739196,  1.87200568, -0.01944214, -0.93259166, -1.29494247,
       -0.1051185 , -1.99496157, -1.30019284,  1.54306765,  1.32326381,
       -0.12841215, -0.46566477,  0.0585089 ,  2.34799693,  0.40497551,
        0.90973817, -0.20245753,  0.06089661,  0.6471627 ,  0.12

In [106]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.